### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Analo-pez/Anonymous-proxy#2]
Muy buen trabajo @Analo-pez!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 275 / 429
- [x] HTML > ATRIBUTOS: Todos los `a` deben tener el atributo `title`.
- [x] HTML > ATRIBUTOS: Todos los `img` deben tener el atributo `title`.
- [x] HTML > ATRIBUTOS: Todos los `img` deben tener el atributo `alt`.
- [x] HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un `nav`.
- [x] HTML > HERO: El texto del título del hero debe ser: Anonymous proxy.
- [x] HTML > HERO: El texto de Anonymous proxy debe estar en un `h1`.
- [x] HTML > HERO: El texto del subtítulo del hero debe ser: In hac habitasse platea dictumst.
- [x] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips".
- [x] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips" que sea un `H2 - H6`.
- [x] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Looking through a window".
- [x] HTML > MÓDULO LOOKING: Debe haber un párrafo con el texto "Donec accumsan...".
- [x] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Lorem ipsum dolor sit amet, consecteur.".
- [x] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Mauris mattis urna quis lorem molestie.".
- [x] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Aliquam in dolor et dolor tincidunt.".
- [x] HTML > FOOTER: Necesitamos una o dos etiquetas `nav` dentro del `footer`.
- [x] HTML > FOOTER: Necesitamos dos `ul` dentro de `nav`.
- [x] HTML > FOOTER: Necesitamos ocho `li` dentro de los `ul`.
- [x] HTML > FOOTER: Necesitamos ocho `a` dentro de los `li`.

- [x] CSS > HERO: El hero debe medir 800px de alto cuando el tamaño de la ventana es 800px.
- [x] CSS > HERO: El hero debe medir 1000px de alto cuando el tamaño de la ventana es 1000px.
- [x] CSS > FOOTER: Alguno de los elementos del footer en tablet deben estar maquetado con flexbox > `order`.
- [x] CSS > TRANSICIONES: Debemos usar alguna transición CSS.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja dímelo cuanto antes por favor.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Anonymous** para buscar el hero. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by Analo-pez** [comment]
@migueldelmazo gracias por las correcciones!!! hay algunas que ya estaban hechas como se pedía, por ejemplo los elementos <ul> <li> <a> del footer, lo demás ya lo he corregido!
Me surge la duda con el tamaño del hero en pantallas de 800 o 1000, entiendo que teniendo en el CSS un height: 100vh;  ya tendría ese comportamiento, así que lo he dejado así!

Gracias!!

**Comment by migueldelmazo** [comment]
Hola @Analo-pez, debería ser así pero no te está funcionando. Si pones el tamaño de ventana en 800x800px el hero mide 768px y debería medir 800px.

Tienes un estilo que es: 
```css
@media (min-width: 768px)
.hero {
  height: 768px;
}
```
Que te está fastidiando...
